config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}

  resources :chat_rooms, only: [:new, :create, :show, :index]

  mount ActionCable.server => '/cable'

  root 'main#index'
  get '/edit_profile' => 'main#user_profile'
  delete '/chat_rooms' => 'main#chat_room_delete'
  delete '/chat_rooms' => 'main#chat_room_clear'
  patch '/edit_profile' => 'main#user_profile_edit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_attached_file :avatar, :styles => {:thumb => "40x40>"}
  validates_attachment :avatar,
                       content_type: { content_type: ["image/jpg","image/jpeg", "image/gif", "image/png","image/pjpeg", "image/x-png"] },
                       :message => 'file type is not allowed (only jpeg/gif/png images)'
  validates_attachment_content_type :avatar, content_type: /\Aimage/
  validates_attachment_file_name :avatar, matches: [/png\z/, /jpe?g\z/]

  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    if user_signed_in?
      User.find_by_id(current_user.id).update_attribute(:room, 0)
      @chat_rooms = ChatRoom.all
      @chat_room = ChatRoom.new
    else
      redirect_to '/users/sign_in'
    end
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Вы создали беседу!'
      redirect_to '/chat_rooms/'+@chat_room.id.to_s
    else
      render 'new'
    end
  end

  def show
    if user_signed_in?
      query = params[:id]
      User.find_by_id(current_user.id).update_attribute(:room, query)
      @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
      redirect_to '/chat_rooms' if @chat_room.nil?
      @message = Message.new
      @user_list = User.where(room: query)
    else
      redirect_to '/'
    end
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    if user_signed_in?
      current_user.first_name.nil? ? (redirect_to '/edit_profile') : (redirect_to '/chat_rooms')
    end
  end

  def user_profile
    @user = User.find_by_id(current_user.id)
  end

  def user_profile_edit
    @user = User.find_by_id(current_user.id)
    @user.update_attributes(profile_params)
    redirect_to '/chat_rooms'
  end

  def chat_room_delete
    id = params[:id]
    chat_room = ChatRoom.find_by_id(id)
    if current_user.admin? || current_user.id == chat_room.user_id
      chat_room.destroy
    end
    redirect_to :back
  end

  private

  def profile_params
    params.require(:user).permit(:first_name, :last_name, :country, :city, :avatar)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

end

app/controllers/registrations_controller.rb
class RegistrationsController < (Devise::RegistrationsController)
  respond_to :html, :json
end

app/controllers/sessions_controller.rb
class SessionsController < (Devise::SessionsController)
  respond_to :html, :json
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chat_rooms/_chat_room.html.erb
  <tr>
    <td>
      <%= link_to t('Enter')+' '+"#{chat_room.title}", chat_room_path(chat_room), :class => '' %>
    </td>
    <td>
      <div class="pull-right">lklkl</div>
    </td>
  </tr>

app/views/chat_rooms/index.html.erb
<%= render "layouts/top-menu" %>
<div class="well">
  <h1><%= t('Chat rooms') %></h1>
  <h2><%= t('Choose your room for chatting') %></h2>
</div>
<div class="container-fluid">
  <div class="row bootstrap snippet">
    <div class="col-sm-12">
      <div class="main-box no-header clearfix">
        <div class="main-box-body clearfix">
          <div class="table-responsive">
            <table class="table user-list">
              <thead>
              <tr>
                <th><span><%= t('Chat name') %></span></th>
                <th><span><%= t('Creator') %></span></th>
                <th><span><%= t('Created at') %></span></th>
                <th><span><%= t('Actions') %></span></th>
                <th>&nbsp;</th>
              </tr>
              </thead>
              <tbody>
              <!-- ADD CHAT ROOMS -->
              <% @chat_rooms.each do |room| %>
                  <tr>
                    <td>
                      <%= room.title %>
                    </td>
                    <td>
                      <%= User.find_by_id(room.user_id).last_name %> <%= User.find_by_id(room.user_id).first_name %>
                    </td>
                    <td>
                      <%= room.created_at.day.to_s+'-'+room.created_at.month.to_s+'-'+room.created_at.year.to_s %>
                    </td>
                    <td>
                      <%= link_to t('Enter'), chat_room_path(room), :class => 'btn btn-success btn-xs' %>
                      <% if current_user.admin? %>
                          <%= button_to t('Delete'), {:controller => :main,
                                                      :action => 'chat_room_delete', :id => room.id},
                                        :method => :delete, data: {confirm: t("Are you sure delete this chat room?")},
                                        :class => 'btn btn-xs btn-danger' %>
                      <% end %>
                    </td>
                  </tr>
              <% end %>
              <!-- END ADD CHAT ROOMS -->
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <p><%= link_to t('New chat room'), "#new_chat", "data-toggle" => "modal", class: 'btn btn-primary btn-success'%></p>
    </div>
  </div>
</div>
<%= render "layouts/new_chat" %>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>
  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<div class="container">
  <%= render "layouts/top-menu" %>
  <h1><%= @chat_room.title %> <%= %></h1>
  <div class="container-fluid">
    <div class="container-fluid">
      <div id="messages" class="col-md-8 well" style="overflow-x: hidden; max-height: 350px" data-chat-room-id="<%= @chat_room.id %>">
        <%= render @chat_room.messages %>
      </div>
      <div class="col-md-3 well pull-right">
        <h2><%= t('User list') %> | <%= @user_list.length %></h2>
        <ul>
          <% @user_list.each do |user| %>
              <li>
                <%= user.first_name %>
              </li>
          <% end %>
          <hr>
          <div class="row">
            <%= link_to t('Exit'), '/chat_rooms',
                          form: {style: 'display:inline-block;'}, data: {confirm: t("Are you sure exit this chat room?")},
                          :class => 'btn btn-xs btn-warning' %>
            <% if current_user.admin? || @chat_room.user_id == current_user.id %>
                <%= button_to t('Delete'), {:controller => :main,
                                            :action => 'chat_room_delete', :id => @chat_room.id},
                              :method => :delete, form: {style: 'display:inline-block;'}, data: {confirm: t("Are you sure delete this chat room?")},
                              :class => 'btn btn-xs btn-danger' %>
            <% end %>
          </div>
        </ul>
      </div>
      <div class="col-md-8 well">
        <%= form_for @message, url: '#' do |f| %>
            <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
            <div class="form-group">
              <%= f.label t(:body) %>
              <%= f.text_area :body, class: 'form-control' %>
              <small class="text-muted"><%= t('From 2 to 1000 characters') %></small>
            </div>

            <%= f.submit t("Post"), class: 'btn btn-primary btn-xs' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/_new_chat.html.erb
<div id="new_chat" class="modal fade">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <!-- Заголовок модального окна -->
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title"><%= t('Create new chat room') %></h4>
      </div>
      <!-- Основное содержимое модального окна -->
      <div class="modal-body">
        <%= form_for @chat_room do |f| %>
            <div class="form-group">
              <%= f.label t(:title) %>
              <%= f.text_field :title, autofocus: true, class: 'form-control' %>
            </div>
            <%= f.submit t("Add"), class: 'btn btn-primary' %>
        <% end %>
      </div>
      <!-- Футер модального окна -->
      <div class="modal-footer">

        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_top-menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><%= label_tag t('By Sparrow R') %></a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/"><%= label_tag t('Home') %></a></li>
    </ul>
    <ul class="nav navbar-nav pull-right">
      <% if user_signed_in? %>
          <li><%= link_to (t('Hello')+', '+ current_user.email+'!'), '#', :class => 'pull-right' %></li>
          <li><%= link_to t("Edit"), '/edit_profile', :method => :get %></li>
          <li><%= link_to t("Log out"), destroy_user_session_path, :method => :delete %></li>
      <% else %>
          <li> <%= link_to (t ("Sign in")), "#sign_in", "data-toggle" => "modal" %> </li>
          <li> <%= link_to (t ("Sign up")), "#sign_up", "data-toggle" => "modal" %> </li>
      <% end %>
    </ul>
  </div>
</nav>
<%= render "devise/shared/sign_in" %>
<%= render "devise/shared/sing_up" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Чат комнаты</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/main/index.html.erb
<%= render "layouts/top-menu" %>
<div class="container-fluid">
  <div class="well text-center">
    <h1><%= label_tag t('Welcome') %></h1>
    <p><%= label_tag t('Please sign in before your actions') %></p>
  </div>
  <div class="container-fluid">
    <div class="center"><h3><%= label_tag t('Three steps for free chatting') %></h3></div>
    <div class="row center-block center">
      <div class="col-sm-4 center">
        <div class="well">
          <h4><%= label_tag t('Sign ups') %></h4>
        </div>
      </div>
      <div class="col-sm-4 center">
        <div class="well">
          <h4><%= label_tag t('Edit profile') %></h4>
        </div>
      </div>
      <div class="col-sm-4 center">
        <div class="well">
          <h4><%= label_tag t('Go chat') %></h4>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/main/user_profile.html.erb
<%= render "layouts/top-menu" %>
<div class="row" style="margin-top: 12.5%">
  <div class="col-xs-9">
    <div class="well" style="min-height: 339px">
      <% if current_user.first_name.nil? %>
          <h1>Осталось всего лишь заполнить профиль</h1>
          <h2 style="color: #3c2d23">И вы сможете общаться</h2>
      <% else %>
          <h1>Редактирование профиля</h1>
          <h2 style="color: #3c2d23">Измените свои данные</h2>
      <% end %>
    </div>
  </div>
  <div class="well center-block col-xs-3">
    <%= form_for(@user, url: {action: "user_profile"}) do |f| %>
        <div class="field center">
          <%= f.label t :first_name %> <br/>
          <%= f.text_field :first_name, :required => true %>
        </div>
        <div class="field center">
          <%= f.label t :last_name %> <br/>
          <%= f.text_field :last_name, :required => true %>
        </div>
        <div class="field center">
          <%= f.label t :country %> <br/>
          <%= f.text_field :country, :required => true %>
        </div>
        <div class="field center">
          <%= f.label t :city %> <br/>
          <%= f.text_field :city, :required => true %>
        </div>
        <div class="field center">
          <%= f.label t :avatar %>
          <%= f.file_field :avatar %>
        </div>
        <br/>
        <div class="actions center">
          <%= f.submit t("Save"), :class => 'btn btn-success btn-sm' %>
        </div>
    <% end %>
  </div>
</div>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <% if message.user.avatar.url == "/avatars/original/missing.png" %>
          <%= gravatar_for message.user %>
        <% else %>
           <img style="max-height: 40px;max-width: 40px" src="<%= message.user.avatar.url(:thumb) %>"/>
        <% end %>
      </div>
      <div class="col-md-8">
        <p class="card-text">
          <span class="text-muted"><%= message.user.first_name %> - <%= message.timestamp %></span><br>
          <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>